targetScope = 'resourceGroup'

@description('Lowercase, unique suffix generated by the local spike runner.')
@minLength(8)
@maxLength(8)
param runSuffix string

@allowed([
  'Consumption'
  'D4'
])
param workloadProfileName string = 'Consumption'

@secure()
@description('Synthetic throwaway value used only by this spike.')
param probeSecret string

@description('SHA-256 digest of the synthetic value; this is not secret material.')
@minLength(64)
@maxLength(64)
param probeDigest string

param location string = 'swedencentral'

var tags = {
  application: 'ghrunners'
  environment: 'spike'
  workload: 'gh-runners'
  owner: 'jonathan-vella'
  costcenter: 'platform-engineering'
  'tech-contact': 'jonathan-vella'
  'technical-contact': 'jonathan-vella'
  sla: 'development'
  'backup-policy': 'none'
  'maint-window': 'none'
}

var vnetName = 'vnet-ghrunners-spike7'
var vaultName = 'kvghr7${runSuffix}'
var environmentName = 'cae-ghr7-${runSuffix}'
var dnsZoneName = 'privatelink.vaultcore.azure.net'
var acaSubnetPrefix = '10.79.0.0/23'
var peSubnetPrefix = '10.79.2.0/24'
var natGatewayName = 'nat-ghr7-${runSuffix}'
var networkSecurityGroupName = 'nsg-ghr7-${runSuffix}'
var keyVaultSecretsUserRoleId = '4633458b-17de-408a-b874-0445c86b69e6'
var consumptionWorkloadProfile = {
  name: 'Consumption'
  workloadProfileType: 'Consumption'
  minimumCount: 0
  maximumCount: 1
}
var d4WorkloadProfile = {
  name: 'D4'
  workloadProfileType: 'D4'
  minimumCount: 0
  maximumCount: 3
}
var workloadProfiles = workloadProfileName == 'D4'
  ? [
      consumptionWorkloadProfile
      d4WorkloadProfile
    ]
  : [
      consumptionWorkloadProfile
    ]

module outboundPublicIp 'br/public:avm/res/network/public-ip-address:0.13.0' = {
  name: 'nat-pip-${runSuffix}'
  params: {
    name: 'pip-ghr7-${runSuffix}'
    location: location
    publicIPAllocationMethod: 'Static'
    skuName: 'Standard'
    skuTier: 'Regional'
    tags: tags
  }
}

module natGateway 'br/public:avm/res/network/nat-gateway:2.1.1' = {
  name: 'nat-gateway-${runSuffix}'
  params: {
    name: natGatewayName
    location: location
    availabilityZone: -1
    publicIpResourceIds: [
      outboundPublicIp.outputs.resourceId
    ]
    tags: tags
  }
}

module acaNetworkSecurityGroup 'br/public:avm/res/network/network-security-group:0.5.3' = {
  name: 'aca-nsg-${runSuffix}'
  params: {
    name: networkSecurityGroupName
    location: location
    securityRules: [
      {
        name: 'Allow-ACA-Platform'
        properties: {
          access: 'Allow'
          destinationAddressPrefix: acaSubnetPrefix
          destinationPortRange: '*'
          direction: 'Outbound'
          priority: 100
          protocol: '*'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
        }
      }
      {
        name: 'Allow-KeyVault-PrivateEndpoint'
        properties: {
          access: 'Allow'
          destinationAddressPrefix: peSubnetPrefix
          destinationPortRange: '443'
          direction: 'Outbound'
          priority: 110
          protocol: 'Tcp'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
        }
      }
      {
        name: 'Allow-Platform-DNS'
        properties: {
          access: 'Allow'
          destinationAddressPrefix: '168.63.129.16/32'
          destinationPortRanges: [
            '53'
          ]
          direction: 'Outbound'
          priority: 120
          protocol: '*'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
        }
      }
      {
        name: 'Allow-HTTPS-Egress-Via-NAT'
        properties: {
          access: 'Allow'
          destinationAddressPrefix: 'Internet'
          destinationPortRange: '443'
          direction: 'Outbound'
          priority: 130
          protocol: 'Tcp'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
        }
      }
      {
        name: 'Deny-RFC1918-10'
        properties: {
          access: 'Deny'
          destinationAddressPrefix: '10.0.0.0/8'
          destinationPortRange: '*'
          direction: 'Outbound'
          priority: 200
          protocol: '*'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
        }
      }
      {
        name: 'Deny-RFC1918-172'
        properties: {
          access: 'Deny'
          destinationAddressPrefix: '172.16.0.0/12'
          destinationPortRange: '*'
          direction: 'Outbound'
          priority: 210
          protocol: '*'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
        }
      }
      {
        name: 'Deny-RFC1918-192'
        properties: {
          access: 'Deny'
          destinationAddressPrefix: '192.168.0.0/16'
          destinationPortRange: '*'
          direction: 'Outbound'
          priority: 220
          protocol: '*'
          sourceAddressPrefix: '*'
          sourcePortRange: '*'
        }
      }
    ]
    tags: tags
  }
}

module virtualNetwork 'br/public:avm/res/network/virtual-network:0.10.2' = {
  name: 'vnet-${runSuffix}'
  params: {
    name: vnetName
    location: location
    addressPrefixes: [
      '10.79.0.0/22'
    ]
    subnets: [
      {
        name: 'snet-aca'
        addressPrefix: acaSubnetPrefix
        delegation: 'Microsoft.App/environments'
        natGatewayResourceId: natGateway.outputs.resourceId
        networkSecurityGroupResourceId: acaNetworkSecurityGroup.outputs.resourceId
      }
      {
        name: 'snet-pe'
        addressPrefix: peSubnetPrefix
        privateEndpointNetworkPolicies: 'Disabled'
      }
    ]
    tags: tags
  }
}

module privateDnsZone 'br/public:avm/res/network/private-dns-zone:0.8.1' = {
  name: 'private-dns-${runSuffix}'
  params: {
    name: dnsZoneName
    location: 'global'
    tags: tags
  }
}

resource privateDnsVnetLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  name: '${dnsZoneName}/link-ghr7-${runSuffix}'
  location: 'global'
  properties: {
    registrationEnabled: false
    virtualNetwork: {
      id: resourceId('Microsoft.Network/virtualNetworks', vnetName)
    }
  }
  dependsOn: [
    privateDnsZone
    virtualNetwork
  ]
}

module testIdentity 'br/public:avm/res/managed-identity/user-assigned-identity:0.6.0' = {
  name: 'identity-${runSuffix}'
  params: {
    name: 'mi-ghr7-${runSuffix}'
    location: location
    tags: tags
  }
}

module keyVault 'br/public:avm/res/key-vault/vault:0.14.2' = {
  name: 'key-vault-${runSuffix}'
  params: {
    name: vaultName
    location: location
    enableRbacAuthorization: true
    enablePurgeProtection: true
    publicNetworkAccess: 'Disabled'
    networkAcls: {
      bypass: 'None'
      defaultAction: 'Deny'
    }
    roleAssignments: [
      {
        name: guid(vaultName, testIdentity.outputs.principalId, keyVaultSecretsUserRoleId)
        principalId: testIdentity.outputs.principalId
        principalType: 'ServicePrincipal'
        roleDefinitionIdOrName: keyVaultSecretsUserRoleId
      }
    ]
    tags: tags
  }
}

resource probeSecretResource 'Microsoft.KeyVault/vaults/secrets@2026-02-01' = {
  name: '${vaultName}/probe'
  properties: {
    value: probeSecret
  }
  dependsOn: [
    keyVault
  ]
}

module privateEndpoint 'br/public:avm/res/network/private-endpoint:0.12.1' = {
  name: 'private-endpoint-${runSuffix}'
  params: {
    name: 'pe-kv-ghr7-${runSuffix}'
    location: location
    subnetResourceId: resourceId('Microsoft.Network/virtualNetworks/subnets', vnetName, 'snet-pe')
    privateLinkServiceConnections: [
      {
        name: 'kv-ghr7-${runSuffix}'
        properties: {
          groupIds: [
            'vault'
          ]
          privateLinkServiceId: keyVault.outputs.resourceId
        }
      }
    ]
    privateDnsZoneGroup: {
      name: 'default'
      privateDnsZoneGroupConfigs: [
        {
          name: 'vault'
          privateDnsZoneResourceId: resourceId('Microsoft.Network/privateDnsZones', dnsZoneName)
        }
      ]
    }
    tags: tags
  }
  dependsOn: [
    privateDnsVnetLink
  ]
}

module containerAppsEnvironment 'br/public:avm/res/app/managed-environment:0.16.0' = {
  name: 'aca-environment-${runSuffix}'
  params: {
    name: environmentName
    location: location
    internal: true
    publicNetworkAccess: 'Disabled'
    infrastructureSubnetResourceId: resourceId('Microsoft.Network/virtualNetworks/subnets', vnetName, 'snet-aca')
    zoneRedundant: workloadProfileName == 'D4' ? false : true
    workloadProfiles: workloadProfiles
    tags: tags
  }
  dependsOn: [
    virtualNetwork
  ]
}

output keyVaultName string = vaultName
output containerAppsEnvironmentName string = environmentName
output testIdentityName string = 'mi-ghr7-${runSuffix}'
output probeDigest string = probeDigest
output workloadProfileName string = workloadProfileName
