targetScope = 'resourceGroup'

@description('Lowercase, unique suffix generated by the local spike runner.')
@minLength(8)
@maxLength(8)
param runSuffix string

@secure()
@description('Synthetic throwaway value used only by this spike.')
param probeSecret string

@description('SHA-256 digest of the synthetic value; this is not secret material.')
@minLength(64)
@maxLength(64)
param probeDigest string

param location string = 'swedencentral'

var tags = {
  application: 'ghrunners'
  environment: 'spike'
  workload: 'gh-runners'
  owner: 'jonathan-vella'
  costcenter: 'platform-engineering'
  'tech-contact': 'jonathan-vella'
  'technical-contact': 'jonathan-vella'
  sla: 'development'
  'backup-policy': 'none'
  'maint-window': 'none'
}

var vnetName = 'vnet-ghrunners-spike7'
var vaultName = 'kvghr7${runSuffix}'
var environmentName = 'cae-ghr7-${runSuffix}'
var jobName = 'caj-ghr7-${runSuffix}'
var dnsZoneName = 'privatelink.vaultcore.azure.net'
var keyVaultSecretsUserRoleId = '4633458b-17de-408a-b874-0445c86b69e6'

module virtualNetwork 'br/public:avm/res/network/virtual-network:0.10.2' = {
  name: 'vnet-${runSuffix}'
  params: {
    name: vnetName
    location: location
    addressPrefixes: [
      '10.79.0.0/22'
    ]
    subnets: [
      {
        name: 'snet-aca'
        addressPrefix: '10.79.0.0/23'
        delegation: 'Microsoft.App/environments'
      }
      {
        name: 'snet-pe'
        addressPrefix: '10.79.2.0/24'
        privateEndpointNetworkPolicies: 'Disabled'
      }
    ]
    tags: tags
  }
}

module privateDnsZone 'br/public:avm/res/network/private-dns-zone:0.8.1' = {
  name: 'private-dns-${runSuffix}'
  params: {
    name: dnsZoneName
    location: 'global'
    tags: tags
  }
}

resource privateDnsVnetLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  name: '${dnsZoneName}/link-ghr7-${runSuffix}'
  location: 'global'
  properties: {
    registrationEnabled: false
    virtualNetwork: {
      id: resourceId('Microsoft.Network/virtualNetworks', vnetName)
    }
  }
  dependsOn: [
    privateDnsZone
    virtualNetwork
  ]
}

module testIdentity 'br/public:avm/res/managed-identity/user-assigned-identity:0.6.0' = {
  name: 'identity-${runSuffix}'
  params: {
    name: 'mi-ghr7-${runSuffix}'
    location: location
    tags: tags
  }
}

module keyVault 'br/public:avm/res/key-vault/vault:0.14.2' = {
  name: 'key-vault-${runSuffix}'
  params: {
    name: vaultName
    location: location
    enableRbacAuthorization: true
    enablePurgeProtection: true
    publicNetworkAccess: 'Disabled'
    networkAcls: {
      bypass: 'None'
      defaultAction: 'Deny'
    }
    roleAssignments: [
      {
        name: guid(vaultName, testIdentity.outputs.principalId, keyVaultSecretsUserRoleId)
        principalId: testIdentity.outputs.principalId
        principalType: 'ServicePrincipal'
        roleDefinitionIdOrName: keyVaultSecretsUserRoleId
      }
    ]
    tags: tags
  }
}

resource probeSecretResource 'Microsoft.KeyVault/vaults/secrets@2026-02-01' = {
  name: '${vaultName}/probe'
  properties: {
    value: probeSecret
  }
  dependsOn: [
    keyVault
  ]
}

module privateEndpoint 'br/public:avm/res/network/private-endpoint:0.12.1' = {
  name: 'private-endpoint-${runSuffix}'
  params: {
    name: 'pe-kv-ghr7-${runSuffix}'
    location: location
    subnetResourceId: resourceId('Microsoft.Network/virtualNetworks/subnets', vnetName, 'snet-pe')
    privateLinkServiceConnections: [
      {
        name: 'kv-ghr7-${runSuffix}'
        properties: {
          groupIds: [
            'vault'
          ]
          privateLinkServiceId: keyVault.outputs.resourceId
        }
      }
    ]
    privateDnsZoneGroup: {
      name: 'default'
      privateDnsZoneGroupConfigs: [
        {
          name: 'vault'
          privateDnsZoneResourceId: resourceId('Microsoft.Network/privateDnsZones', dnsZoneName)
        }
      ]
    }
    tags: tags
  }
  dependsOn: [
    privateDnsVnetLink
  ]
}

module containerAppsEnvironment 'br/public:avm/res/app/managed-environment:0.16.0' = {
  name: 'aca-environment-${runSuffix}'
  params: {
    name: environmentName
    location: location
    internal: true
    publicNetworkAccess: 'Disabled'
    infrastructureSubnetResourceId: resourceId('Microsoft.Network/virtualNetworks/subnets', vnetName, 'snet-aca')
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
        minimumCount: 0
        maximumCount: 1
      }
    ]
    tags: tags
  }
  dependsOn: [
    virtualNetwork
  ]
}

module diagnosticJob 'br/public:avm/res/app/job:0.7.2' = {
  name: 'aca-job-${runSuffix}'
  params: {
    name: jobName
    location: location
    environmentResourceId: containerAppsEnvironment.outputs.resourceId
    triggerType: 'Manual'
    managedIdentities: {
      userAssignedResourceIds: [
        testIdentity.outputs.resourceId
      ]
    }
    replicaRetryLimit: 0
    replicaTimeout: 300
    manualTriggerConfig: {
      parallelism: 1
      replicaCompletionCount: 1
    }
    secrets: [
      {
        name: 'probe'
        identity: testIdentity.outputs.resourceId
        keyVaultUrl: '${keyVault.outputs.uri}secrets/probe'
      }
    ]
    containers: [
      {
        name: 'probe'
        image: 'mcr.microsoft.com/azure-cli@sha256:933eb8dcb81aecb6f77e03c5b8660f0a1dfa9e1d16525763a27f86ff3b83a044'
        command: [
          '/bin/sh'
          '-c'
        ]
        args: [
          'actual="$(printf "%s" "$PROBE_SECRET" | sha256sum | cut -d " " -f 1)"; if [ "$actual" = "$EXPECTED_SHA256" ]; then printf "RESULT=match\\n"; else printf "RESULT=mismatch\\n"; exit 1; fi'
        ]
        env: [
          {
            name: 'PROBE_SECRET'
            secretRef: 'probe'
          }
          {
            name: 'EXPECTED_SHA256'
            value: probeDigest
          }
        ]
        resources: {
          cpu: '0.25'
          memory: '0.5Gi'
        }
      }
    ]
    tags: tags
  }
  dependsOn: [
    probeSecretResource
    privateEndpoint
  ]
}

output keyVaultName string = vaultName
output containerAppsEnvironmentName string = environmentName
output diagnosticJobName string = jobName
